game:
  id: '21779'
  name: League of Legends
clips:
  count: 100
  age_days: 3
  max_duration: 600
  min_views: 50
filter:
  motion_threshold: 10.0
  talking_clips_language: en
output:
  clips_folder: ./clips
  width: 1920
  height: 1080
  fps: 30
  use_hw_accel: true
processing:
  max_workers: 6
